name: Fabrício Ronchi - Blog
pygments: true
name: Fabrício Ronchi
url: http://blog.fabricioronchi.com
domain: blog.fabricioronchi.com
author :
  name : Fabrício Ronchi
  email : me@fabricioronchi.com
  github : https://github.com/realronchi
  twitter : https://twitter.com/realronchi
  linkedin : http://br.linkedin.com/in/realronchi
